# Docker Compose configuration for Social Media App

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: social_media_postgres
    environment:
      POSTGRES_DB: social_media_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/migrations:/docker-entrypoint-initdb.d
    networks:
      - social_media_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: social_media_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - social_media_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social_media_backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=social_media_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-here
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
    networks:
      - social_media_network

  # React Native Metro Bundler (for development)
  metro:
    build:
      context: .
      dockerfile: Dockerfile.metro
    container_name: social_media_metro
    ports:
      - "8082:8081"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - social_media_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: social_media_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - social_media_network

volumes:
  postgres_data:
  redis_data:

networks:
  social_media_network:
    driver: bridge
