apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: social-media
data:
  NODE_ENV: production
  PORT: "3000"
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: social_media_db
  DB_USER: postgres
  DB_PASSWORD: password
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  JWT_SECRET: your-super-secret-jwt-key-here
  JWT_REFRESH_SECRET: your-super-secret-refresh-key-here
  JWT_EXPIRES_IN: 1h
  JWT_REFRESH_EXPIRES_IN: 7d

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: social-media
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: social-media-backend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: social-media
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
